project:
  type: website

website:
  title: "Landlords"
  reader-mode: true
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/g4brielvs/landlords
    sidebar:
      style: "floating"
      contents:
        - section: "Basics"
          contents:
            - brief.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



