# Book settings
title:
author: Gabriel Stefanini Vicente
logo: docs/images/logo.png
only_build_toc_files: false

repository:
  url: https://github.com/g4brielvs/landlords
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: true
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://g4brielvs.github.io/landlords
  favicon: docs/images/favicon.ico

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  recursive_update: true
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
    html_js_files:
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
